# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mine Wyrtruman
byline: Where ancient spirituality meets modern praxis
footer: © 2022 by Byron Pendason. Except where noted otherwise, every statement on this blog reflects my own views. I am neither am expert nor an academic, so I encourage you to double check everything in order to arrive at your own conclusions. If you find the information on this site helpful, please consider <a href="https://ko-fi.com/ByronTheFyrnsidere">buying me a coffee.</a>
email: byronpendason@minewyrtruman.com
description: Mine Wyrtruman explores the roots of Fyrnsidu in order to discover how to apply them to modern spirituality.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.minewyrtruman.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: byronfyrnsidere
github_username:  byronpendason
show_excerpts: true
permalink: /:year/:month/:day/:title/
collections:
  wiki:
    output: true
    permalink: /wiki/:title
defaults
  - scope:
      path: " "
      type: "wiki"
    values:
      layout: "default"
header_pages:
  - title: Home
    url: /
  - title: Blog
    url: /blog
  - title: About
    url: /about
  - title: Contact Me
    url: /contact
  - title: Search Site
    url: /search
  - title: Glossary and Resources for Beginners
    url: /glossary
  - title: Blog Post Requests
    url: /requests
  - title: The Reconstructed Anglo-Saxon Calendar
    url: /anglosaxoncalendar
  - title: A Ritual of Thanksgiving
    url: /ritual_of_thanksgiving
  - title: Declaration of Deeds 
    url: /declaration-of-deeds
  - title: RuneTyper
    url: /runetyper
plugins:
  - jekyll-feed
# Analytics
google_analytics: 'G-SE3GMKHNJ4'
  

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
